# Generated by Django 4.1.2 on 2024-03-12 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('tell', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('tell', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(default='', max_length=100)),
                ('rateReceive', models.IntegerField(default=0)),
                ('rateSend', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SendOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.customer')),
                ('inv_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.inventorystock')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.customer')),
                ('inv_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.inventorystock')),
            ],
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.type'),
        ),
    ]
