# Generated by Django 4.1.2 on 2024-03-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveorder',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='receiveorder',
            name='emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.employee'),
        ),
    ]
