# Generated by Django 5.0.2 on 2024-03-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autiqueApp', '0002_alter_receiveorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receiveorder',
            name='cus_id',
        ),
        migrations.RemoveField(
            model_name='receiveorder',
            name='inv_id',
        ),
        migrations.CreateModel(
            name='ReceiveDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cus_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.customer')),
                ('inv_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.inventorystock')),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.receiveorder')),
            ],
        ),
    ]
