# Generated by Django 4.1.2 on 2024-03-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autiqueApp', '0002_remove_receiveorder_cus_id_receiveorder_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveorder',
            old_name='emp',
            new_name='emp_id',
        ),
    ]
