# Generated by Django 4.1.2 on 2024-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autiqueApp', '0003_rename_emp_receiveorder_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveorder',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='sendorder',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='receiveorder',
            name='cus_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.customer'),
        ),
        migrations.AddField(
            model_name='sendorder',
            name='emp_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autiqueApp.employee'),
        ),
    ]
