# Generated by Django 5.0.2 on 2024-03-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autiqueApp', '0003_remove_receiveorder_amount_and_more'),
        ('autiqueApp', '0004_remove_receiveorder_emp_id_remove_sendorder_cus_id_and_more'),
    ]

    operations = [
    ]
